// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InsertTodo struct {
	Description string `json:"description"`
}

type Todo struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Completed   bool   `json:"completed"`
}

type UpdateTodo struct {
	ID          string  `json:"id"`
	Description *string `json:"description"`
	Completed   *bool   `json:"completed"`
}
