name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Install PNMP
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      
      - uses: actions/checkout@v2
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build:docker
